title: Yurii Kolesnykov
description: Senior iOS / Mobile Software Engineer
show_downloads: true
remote_theme: pages-themes/hacker@v0.2.0
github:
  pdf_url: "/Yurii Kolesnykov â€” Senior iOS Software Engineer.pdf"
